import '../models/contact_model.dart';

class ContactService {
  static const List<Map<String, String>> criticalContacts = [
    {
      'organisation': 'জাতীয় জরুরি সেবা',
      'phone': '999',
      'description': 'পুলিশ, অগ্নিনির্বাপক ও অ্যাম্বুলেন্স',
    },
    {
      'organisation': 'অগ্নিনির্বাপক সেবা',
      'phone': '16163',
      'description': 'অগ্নিনির্বাপক কন্ট্রোল রুম',
    },
    {
      'organisation': 'দুর্যোগ হেল্পলাইন',
      'phone': '1090',
      'description': 'দুর্যোগ ব্যবস্থাপনা বিভাগ',
    },
  ];

  // Translation maps for UI display
  static const Map<String, String> divisionsBangla = {
    'Barisal': 'বরিশাল',
    'Chittagong': 'চট্টগ্রাম',
    'Dhaka': 'ঢাকা',
    'Khulna': 'খুলনা',
    'Mymensingh': 'ময়মনসিংহ',
    'Rajshahi': 'রাজশাহী',
    'Rangpur': 'রংপুর',
    'Sylhet': 'সিলেট',
  };

  static const Map<String, String> districtsBangla = {
    'Bagerhat': 'বাগেরহাট',
    'Bandarban': 'বান্দরবান',
    'Barguna': 'বরগুনা',
    'Barisal': 'বরিশাল',
    'Bhola': 'ভোলা',
    'Bogra': 'বগুড়া',
    'Brahmanbaria': 'ব্রাহ্মণবাড়িয়া',
    'Chandpur': 'চাঁদপুর',
    'Chapainawabganj': 'চাঁপাইনবাবগঞ্জ',
    'Chittagong': 'চট্টগ্রাম',
    'Chuadanga': 'চুয়াডাঙ্গা',
    'Comilla': 'কুমিল্লা',
    "Cox's Bazar": 'কক্সবাজার',
    'Dhaka': 'ঢাকা',
    'Dinajpur': 'দিনাজপুর',
    'Faridpur': 'ফরিদপুর',
    'Feni': 'ফেনী',
    'Gaibandha': 'গাইবান্ধা',
    'Gazipur': 'গাজীপুর',
    'Gopalganj': 'গোপালগঞ্জ',
    'Habiganj': 'হবিগঞ্জ',
    'Jamalpur': 'জামালপুর',
    'Jessore': 'যশোর',
    'Jhalokati': 'ঝালকাঠি',
    'Jhenaidah': 'ঝিনাইদহ',
    'Joypurhat': 'জয়পুরহাট',
    'Khagrachhari': 'খাগড়াছড়ি',
    'Khulna': 'খুলনা',
    'Kishoreganj': 'কিশোরগঞ্জ',
    'Kurigram': 'কুড়িগ্রাম',
    'Kushtia': 'কুষ্টিয়া',
    'Lakshmipur': 'লক্ষ্মীপুর',
    'Lalmonirhat': 'লালমনিরহাট',
    'Madaripur': 'মাদারীপুর',
    'Magura': 'মাগুরা',
    'Manikganj': 'মানিকগঞ্জ',
    'Meherpur': 'মেহেরপুর',
    'Moulvibazar': 'মৌলভীবাজার',
    'Munshiganj': 'মুন্সিগঞ্জ',
    'Mymensingh': 'ময়মনসিংহ',
    'Naogaon': 'নওগাঁ',
    'Narail': 'নড়াইল',
    'Narayanganj': 'নারায়ণগঞ্জ',
    'Narsingdi': 'নরসিংদী',
    'Natore': 'নাটোর',
    'Netrokona': 'নেত্রকোনা',
    'Nilphamari': 'নীলফামারী',
    'Noakhali': 'নোয়াখালী',
    'Pabna': 'পাবনা',
    'Panchagarh': 'পঞ্চগড়',
    'Patuakhali': 'পটুয়াখালী',
    'Pirojpur': 'পিরোজপুর',
    'Rajbari': 'রাজবাড়ী',
    'Rajshahi': 'রাজশাহী',
    'Rangamati': 'রাঙ্গামাটি',
    'Rangpur': 'রংপুর',
    'Satkhira': 'সাতক্ষীরা',
    'Shariatpur': 'শরীয়তপুর',
    'Sherpur': 'শেরপুর',
    'Sirajganj': 'সিরাজগঞ্জ',
    'Sunamganj': 'সুনামগঞ্জ',
    'Sylhet': 'সিলেট',
    'Tangail': 'টাঙ্গাইল',
    'Thakurgaon': 'ঠাকুরগাঁও',
  };

  static const Map<String, String> upazilasBangla = {
    'Dhanmondi': 'ধনমন্দি',
    'Gulshan': 'গুলশান',
    'Mirpur': 'মিরপুর',
    'Mohammadpur': 'মোহাম্মদপুর',
    'Uttara': 'উত্তরা',
    'Motijheel': 'মতিঝিল',
    'Chandgaon': 'চাঁদগাঁও',
    'Double Mooring': 'ডাবল মুরিং',
    'Kotwali': 'কোতওয়ালী',
    'Panchlaish': 'পাঁচলাইশ',
    'Pahartali': 'পাহাড়তলী',
    "Cox's Bazar Sadar": 'কক্সবাজার সদর',
    'Ramu': 'রামু',
    'Teknaf': 'টেকনাফ',
    'Ukhia': 'উখিয়া',
    'Chakaria': 'চকরিয়া',
    'Khulna Sadar': 'খুলনা সদর',
    'Sonadanga': 'সোনাদাঙ্গা',
    'Khalishpur': 'খালিশপুর',
    'Daulatpur': 'দৌলতপুর',
    'Barisal Sadar': 'বরিশাল সদর',
    'Bakerganj': 'বাকেরগঞ্জ',
    'Babuganj': 'বাবুগঞ্জ',
    'Agailjhara': 'আগৈলঝাড়া',
    'Sylhet Sadar': 'সিলেট সদর',
    'Beanibazar': 'বিয়ানীবাজার',
    'Bishwanath': 'বিশ্বনাথ',
    'Golapganj': 'গোলাপগঞ্জ',
    'Rajshahi Sadar': 'রাজশাহী সদর',
    'Boalia': 'বোয়ালিয়া',
    'Rajpara': 'রাজপাড়া',
    'Shah Makhdum': 'শাহ মখদুম',
    'Rangpur Sadar': 'রংপুর সদর',
    'Gangachara': 'গঙ্গাচড়া',
    'Taragram': 'তারাগ্রাম',
    'Badarganj': 'বদরগঞ্জ',
    'Mymensingh Sadar': 'ময়মনসিংহ সদর',
    'Trishal': 'ত্রিশাল',
    'Bhaluka': 'ভালুকা',
    'Gaffargaon': 'গফরগাঁও',
    'Gazipur Sadar': 'গাজীপুর সদর',
    'Kaliakair': 'কালিয়াকৈর',
    'Kapasia': 'কাপাসিয়া',
    'Sreepur': 'শ্রীপুর',
    'Noakhali Sadar': 'নোয়াখালী সদর',
    'Hatiya': 'হাতিয়া',
    'Senbagh': 'সেনবাঘ',
    'Companiganj': 'কোম্পানীগঞ্জ',
    'Comilla Sadar': 'কুমিল্লা সদর',
    'Daudkandi': 'দাউদকান্দি',
    'Chandina': 'চাঁদিনা',
    'Laksam': 'লাকসাম',
  };

  Future<List<String>> fetchDivisions() async => List.from(_seedDivisions);
  Future<List<String>> fetchDistricts(String division) async =>
      List.from(_seedDistricts[division] ?? []);
  Future<List<String>> fetchUpazilas(String division, String district) async =>
      _demoUpazilas(district);

  Future<List<EmergencyContact>> fetchContacts({
    required String division,
    required String district,
    required String upazila,
  }) async => _demoContacts(division, district, upazila);

  static List<String> _demoUpazilas(String district) {
    final map = <String, List<String>>{
      'Dhaka': [
        'Dhanmondi',
        'Gulshan',
        'Mirpur',
        'Mohammadpur',
        'Uttara',
        'Motijheel',
      ],
      'Chittagong': [
        'Chandgaon',
        'Double Mooring',
        'Kotwali',
        'Panchlaish',
        'Pahartali',
      ],
      "Cox's Bazar": [
        "Cox's Bazar Sadar",
        'Ramu',
        'Teknaf',
        'Ukhia',
        'Chakaria',
      ],
      'Khulna': ['Khulna Sadar', 'Sonadanga', 'Khalishpur', 'Daulatpur'],
      'Barisal': ['Barisal Sadar', 'Bakerganj', 'Babuganj', 'Agailjhara'],
      'Sylhet': ['Sylhet Sadar', 'Beanibazar', 'Bishwanath', 'Golapganj'],
      'Rajshahi': ['Rajshahi Sadar', 'Boalia', 'Rajpara', 'Shah Makhdum'],
      'Rangpur': ['Rangpur Sadar', 'Gangachara', 'Taragram', 'Badarganj'],
      'Mymensingh': ['Mymensingh Sadar', 'Trishal', 'Bhaluka', 'Gaffargaon'],
      'Gazipur': ['Gazipur Sadar', 'Kaliakair', 'Kapasia', 'Sreepur'],
      'Noakhali': ['Noakhali Sadar', 'Hatiya', 'Senbagh', 'Companiganj'],
      'Comilla': ['Comilla Sadar', 'Daudkandi', 'Chandina', 'Laksam'],
    };
    return map[district] ?? ['$district Sadar', 'Upazila 2', 'Upazila 3'];
  }

  static List<EmergencyContact> _demoContacts(
    String division,
    String district,
    String upazila,
  ) {
    return [
      EmergencyContact(
        id: 'd1',
        division: division,
        district: district,
        upazila: upazila,
        organisation: '$district জেলা হাসপাতাল',
        phone: '01700-000001',
        description: 'সরকারি জেলা হাসপাতাল - ২৪ ঘন্টা জরুরি সেবা',
      ),
      EmergencyContact(
        id: 'd2',
        division: division,
        district: district,
        upazila: upazila,
        organisation: '$district অগ্নিনির্বাপক সেবা',
        phone: '01700-000002',
        description: 'স্থানীয় অগ্নিনির্বাপক ও বেসামরিক প্রতিরক্ষা',
      ),
      EmergencyContact(
        id: 'd3',
        division: division,
        district: district,
        upazila: upazila,
        organisation: '$upazila থানা',
        phone: '01700-000003',
        description: 'স্থানীয় আইন শৃঙ্খলা বাহিনী',
      ),
      EmergencyContact(
        id: 'd4',
        division: division,
        district: district,
        upazila: upazila,
        organisation: 'ঘূর্ণিঝড় প্রস্তুতি কর্মসূচি',
        phone: '01700-000004',
        description: 'বাংলাদেশ রেডক্রস সিপিপি স্বয়ংসেবক',
      ),
      EmergencyContact(
        id: 'd5',
        division: division,
        district: district,
        upazila: upazila,
        organisation: '$district দুর্যোগ ব্যবস্থাপনা অফিস',
        phone: '01700-000005',
        description: 'জেলা দুর্যোগ ব্যবস্থাপনা কমিটি',
      ),
    ];
  }

  static const List<String> _seedDivisions = [
    'Barisal',
    'Chittagong',
    'Dhaka',
    'Khulna',
    'Mymensingh',
    'Rajshahi',
    'Rangpur',
    'Sylhet',
  ];

  static const Map<String, List<String>> _seedDistricts = {
    "Chittagong": [
      "Cox's Bazar",
      'Chittagong',
      'Bandarban',
      'Rangamati',
      'Khagrachhari',
      'Feni',
      'Noakhali',
      'Lakshmipur',
      'Comilla',
      'Chandpur',
      'Brahmanbaria',
    ],
    'Dhaka': [
      'Dhaka',
      'Gazipur',
      'Narayanganj',
      'Manikganj',
      'Munshiganj',
      'Narsingdi',
      'Tangail',
      'Kishoreganj',
    ],
    'Khulna': [
      'Khulna',
      'Bagerhat',
      'Satkhira',
      'Jessore',
      'Narail',
      'Magura',
      'Jhenaidah',
      'Kushtia',
      'Chuadanga',
      'Meherpur',
    ],
    'Barisal': [
      'Barisal',
      'Bhola',
      'Patuakhali',
      'Pirojpur',
      'Jhalokati',
      'Barguna',
    ],
    'Sylhet': ['Sylhet', 'Moulvibazar', 'Habiganj', 'Sunamganj'],
    'Rajshahi': [
      'Rajshahi',
      'Chapainawabganj',
      'Natore',
      'Naogaon',
      'Bogra',
      'Joypurhat',
      'Sirajganj',
      'Pabna',
    ],
    'Rangpur': [
      'Rangpur',
      'Gaibandha',
      'Kurigram',
      'Lalmonirhat',
      'Nilphamari',
      'Panchagarh',
      'Thakurgaon',
      'Dinajpur',
    ],
    'Mymensingh': ['Mymensingh', 'Sherpur', 'Jamalpur', 'Netrokona'],
  };
}
