// Service for fetching shelter (সাইক্লোন আশ্রয়কেন্দ্র / school) data.
import 'dart:math';
import '../models/shelter_model.dart';

class ShelterService {
  static final List<Shelter> _seedShelters = [
    // বাগেরহাট
    const Shelter(
      id: 'bgh1',
      name: 'বাগেরহাট সরকারি উচ্চ বিদ্যালয়',
      address: 'বাগেরহাট সদর',
      lat: 22.6602,
      lng: 89.7806,
      district: 'bagerhat',
      capacity: 600,
    ),
    const Shelter(
      id: 'bgh2',
      name: 'মোল্লাহাট উপজেলা সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'মোল্লাহাট, বাগেরহাট',
      lat: 22.7100,
      lng: 89.8400,
      district: 'bagerhat',
      capacity: 450,
    ),
    const Shelter(
      id: 'bgh3',
      name: 'রামপাল উপকূলীয় আশ্রয়কেন্দ্র',
      address: 'রামপাল, বাগেরহাট',
      lat: 22.6000,
      lng: 89.7200,
      district: 'bagerhat',
      capacity: 400,
    ),
    // বান্দরবান
    const Shelter(
      id: 'bdb1',
      name: 'বান্দরবান সদর উচ্চ বিদ্যালয় আশ্রয়কেন্দ্র',
      address: 'বান্দরবান সদর',
      lat: 22.1953,
      lng: 92.2184,
      district: 'bandarban',
      capacity: 350,
    ),
    const Shelter(
      id: 'bdb2',
      name: 'লামা উপজেলা কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'লামা, বান্দরবান',
      lat: 21.9970,
      lng: 92.2080,
      district: 'bandarban',
      capacity: 300,
    ),
    const Shelter(
      id: 'bdb3',
      name: 'রুমা বন্যা আশ্রয়কেন্দ্র',
      address: 'রুমা, বান্দরবান',
      lat: 22.0880,
      lng: 92.3460,
      district: 'bandarban',
      capacity: 280,
    ),
    // বরগুনা
    const Shelter(
      id: 'brg1',
      name: 'বরগুনা সরকারি উচ্চ বিদ্যালয়',
      address: 'বরগুনা শহর',
      lat: 22.0959,
      lng: 90.1120,
      district: 'barguna',
      capacity: 600,
    ),
    const Shelter(
      id: 'brg2',
      name: 'আমতলী উপজেলা সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'আমতলী, বরগুনা',
      lat: 22.0700,
      lng: 90.2300,
      district: 'barguna',
      capacity: 450,
    ),
    const Shelter(
      id: 'brg3',
      name: 'পাথরঘাটা উপকূলীয় আশ্রয়কেন্দ্র',
      address: 'পাথরঘাটা, বরগুনা',
      lat: 21.8470,
      lng: 90.0140,
      district: 'barguna',
      capacity: 500,
    ),
    // বরিশাল
    const Shelter(
      id: 'brs1',
      name: 'বরিশাল কলেজিয়েট স্কুল',
      address: 'বরিশাল শহর',
      lat: 22.7010,
      lng: 90.3535,
      district: 'barisal',
      capacity: 600,
    ),
    const Shelter(
      id: 'brs2',
      name: 'বাকেরগঞ্জ উপজেলা আশ্রয়কেন্দ্র',
      address: 'বাকেরগঞ্জ, বরিশাল',
      lat: 22.6500,
      lng: 90.2300,
      district: 'barisal',
      capacity: 450,
    ),
    const Shelter(
      id: 'brs3',
      name: 'মেহেন্দিগঞ্জ সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'মেহেন্দিগঞ্জ, বরিশাল',
      lat: 22.5200,
      lng: 90.4100,
      district: 'barisal',
      capacity: 500,
    ),
    // ভোলা
    const Shelter(
      id: 'bhl1',
      name: 'ভোলা সরকারি কলেজ আশ্রয়কেন্দ্র',
      address: 'ভোলা সদর',
      lat: 22.6859,
      lng: 90.6482,
      district: 'bhola',
      capacity: 800,
    ),
    const Shelter(
      id: 'bhl2',
      name: 'চরফ্যাশন সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'চরফ্যাশন, ভোলা',
      lat: 22.1900,
      lng: 90.7400,
      district: 'bhola',
      capacity: 600,
    ),
    const Shelter(
      id: 'bhl3',
      name: 'দৌলতখান উপকূলীয় আশ্রয়কেন্দ্র',
      address: 'দৌলতখান, ভোলা',
      lat: 22.5050,
      lng: 90.7010,
      district: 'bhola',
      capacity: 500,
    ),
    // বগুড়া
    const Shelter(
      id: 'bgr1',
      name: 'বগুড়া জিলা স্কুল আশ্রয়কেন্দ্র',
      address: 'বগুড়া সদর',
      lat: 24.8465,
      lng: 89.3720,
      district: 'bogra',
      capacity: 600,
    ),
    const Shelter(
      id: 'bgr2',
      name: 'শেরপুর উপজেলা বন্যা আশ্রয়কেন্দ্র',
      address: 'শেরপুর, বগুড়া',
      lat: 24.9200,
      lng: 89.3500,
      district: 'bogra',
      capacity: 400,
    ),
    const Shelter(
      id: 'bgr3',
      name: 'শিবগঞ্জ সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'শিবগঞ্জ, বগুড়া',
      lat: 24.7700,
      lng: 88.9900,
      district: 'bogra',
      capacity: 380,
    ),
    // ব্রাহ্মণবাড়িয়া
    const Shelter(
      id: 'brb1',
      name: 'ব্রাহ্মণবাড়িয়া সরকারি কলেজ আশ্রয়কেন্দ্র',
      address: 'ব্রাহ্মণবাড়িয়া সদর',
      lat: 23.9571,
      lng: 91.1115,
      district: 'brahmanbaria',
      capacity: 650,
    ),
    const Shelter(
      id: 'brb2',
      name: 'কসবা উপজেলা কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'কসবা, ব্রাহ্মণবাড়িয়া',
      lat: 23.8790,
      lng: 91.0890,
      district: 'brahmanbaria',
      capacity: 400,
    ),
    const Shelter(
      id: 'brb3',
      name: 'নবীনগর বন্যা আশ্রয়কেন্দ্র',
      address: 'নবীনগর, ব্রাহ্মণবাড়িয়া',
      lat: 23.8250,
      lng: 90.9700,
      district: 'brahmanbaria',
      capacity: 420,
    ),
    // চাঁদপুর
    const Shelter(
      id: 'cdp1',
      name: 'চাঁদপুর সরকারি উচ্চ বিদ্যালয়',
      address: 'চাঁদপুর সদর',
      lat: 23.2323,
      lng: 90.6717,
      district: 'chandpur',
      capacity: 600,
    ),
    const Shelter(
      id: 'cdp2',
      name: 'হাইমচর সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'হাইমচর, চাঁদপুর',
      lat: 23.1300,
      lng: 90.6800,
      district: 'chandpur',
      capacity: 450,
    ),
    const Shelter(
      id: 'cdp3',
      name: 'মতলব বন্যা আশ্রয়কেন্দ্র',
      address: 'মতলব, চাঁদপুর',
      lat: 23.3800,
      lng: 90.6900,
      district: 'chandpur',
      capacity: 480,
    ),
    // চাঁপাইনবাবগঞ্জ
    const Shelter(
      id: 'cpn1',
      name: 'চাঁপাইনবাবগঞ্জ সরকারি কলেজ',
      address: 'চাঁপাইনবাবগঞ্জ সদর',
      lat: 24.5965,
      lng: 88.2778,
      district: 'chapainawabganj',
      capacity: 500,
    ),
    const Shelter(
      id: 'cpn2',
      name: 'শিবগঞ্জ উপজেলা আশ্রয়কেন্দ্র',
      address: 'শিবগঞ্জ, চাঁপাইনবাবগঞ্জ',
      lat: 24.6600,
      lng: 88.1600,
      district: 'chapainawabganj',
      capacity: 380,
    ),
    const Shelter(
      id: 'cpn3',
      name: 'গোমস্তাপুর কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'গোমস্তাপুর, চাঁপাইনবাবগঞ্জ',
      lat: 24.8450,
      lng: 88.2300,
      district: 'chapainawabganj',
      capacity: 350,
    ),
    // চট্টগ্রাম
    const Shelter(
      id: 'ctg1',
      name: 'চট্টগ্রাম কলেজিয়েট স্কুল',
      address: 'Anderkilla, চট্টগ্রাম',
      lat: 22.3569,
      lng: 91.7832,
      district: 'chittagong',
      capacity: 1000,
    ),
    const Shelter(
      id: 'ctg2',
      name: 'নাসিরাবাদ সরকারি উচ্চ বিদ্যালয়',
      address: 'নাসিরাবাদ, চট্টগ্রাম',
      lat: 22.3750,
      lng: 91.8280,
      district: 'chittagong',
      capacity: 750,
    ),
    const Shelter(
      id: 'ctg3',
      name: 'হাটহাজারী সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'হাটহাজারী, চট্টগ্রাম',
      lat: 22.5110,
      lng: 91.8090,
      district: 'chittagong',
      capacity: 800,
    ),
    // চুয়াডাঙ্গা
    const Shelter(
      id: 'cha1',
      name: 'চুয়াডাঙ্গা সরকারি উচ্চ বিদ্যালয়',
      address: 'চুয়াডাঙ্গা সদর',
      lat: 23.6402,
      lng: 88.8416,
      district: 'chuadanga',
      capacity: 500,
    ),
    const Shelter(
      id: 'cha2',
      name: 'দামুড়হুদা উপজেলা আশ্রয়কেন্দ্র',
      address: 'দামুড়হুদা, চুয়াডাঙ্গা',
      lat: 23.5900,
      lng: 88.9000,
      district: 'chuadanga',
      capacity: 360,
    ),
    const Shelter(
      id: 'cha3',
      name: 'আলমডাঙ্গা কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'আলমডাঙ্গা, চুয়াডাঙ্গা',
      lat: 23.7260,
      lng: 88.9350,
      district: 'chuadanga',
      capacity: 340,
    ),
    // কুমিল্লা
    const Shelter(
      id: 'cml1',
      name: 'কুমিল্লা ভিক্টোরিয়া সরকারি কলেজ',
      address: 'Kandirpar, কুমিল্লা',
      lat: 23.4607,
      lng: 91.1809,
      district: 'comilla',
      capacity: 800,
    ),
    const Shelter(
      id: 'cml2',
      name: 'লাকসাম সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'লাকসাম, কুমিল্লা',
      lat: 23.2350,
      lng: 91.1280,
      district: 'comilla',
      capacity: 500,
    ),
    const Shelter(
      id: 'cml3',
      name: 'চৌদ্দগ্রাম বন্যা আশ্রয়কেন্দ্র',
      address: 'চৌদ্দগ্রাম, কুমিল্লা',
      lat: 23.2100,
      lng: 91.2000,
      district: 'comilla',
      capacity: 480,
    ),
    // কক্সবাজার
    const Shelter(
      id: 'cxb1',
      name: "কক্সবাজার সরকারি উচ্চ বিদ্যালয়",
      address: "Main Road, কক্সবাজার",
      lat: 21.4272,
      lng: 92.0058,
      district: "cox's bazar",
      capacity: 800,
    ),
    const Shelter(
      id: 'cxb2',
      name: 'রামু সাইক্লোন আশ্রয়কেন্দ্র',
      address: "রামু, কক্সবাজার",
      lat: 21.4555,
      lng: 92.0780,
      district: "cox's bazar",
      capacity: 600,
    ),
    const Shelter(
      id: 'cxb3',
      name: 'টেকনাফ উপকূলীয় আশ্রয়কেন্দ্র',
      address: "টেকনাফ, কক্সবাজার",
      lat: 20.8644,
      lng: 92.3021,
      district: "cox's bazar",
      capacity: 550,
    ),
    // ঢাকা
    const Shelter(
      id: 'dha1',
      name: 'বংশাল সরকারি প্রাথমিক বিদ্যালয়',
      address: 'বংশাল, ঢাকা',
      lat: 23.7200,
      lng: 90.4080,
      district: 'dhaka',
      capacity: 500,
    ),
    const Shelter(
      id: 'dha2',
      name: 'ডেমরা উচ্চ বিদ্যালয় সাইক্লোন কেন্দ্র',
      address: 'ডেমরা, ঢাকা',
      lat: 23.7105,
      lng: 90.4644,
      district: 'dhaka',
      capacity: 600,
    ),
    const Shelter(
      id: 'dha3',
      name: 'মিরপুর সরকারি স্কুল আশ্রয়কেন্দ্র',
      address: 'মিরপুর, ঢাকা',
      lat: 23.8223,
      lng: 90.3654,
      district: 'dhaka',
      capacity: 450,
    ),
    // দিনাজপুর
    const Shelter(
      id: 'dnj1',
      name: 'দিনাজপুর সরকারি কলেজ আশ্রয়কেন্দ্র',
      address: 'দিনাজপুর সদর',
      lat: 25.6279,
      lng: 88.6338,
      district: 'dinajpur',
      capacity: 600,
    ),
    const Shelter(
      id: 'dnj2',
      name: 'বিরামপুর উপজেলা বন্যা আশ্রয়কেন্দ্র',
      address: 'বিরামপুর, দিনাজপুর',
      lat: 25.5200,
      lng: 88.7200,
      district: 'dinajpur',
      capacity: 400,
    ),
    const Shelter(
      id: 'dnj3',
      name: 'ফুলবাড়ী কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'ফুলবাড়ী, দিনাজপুর',
      lat: 25.7900,
      lng: 88.5900,
      district: 'dinajpur',
      capacity: 380,
    ),
    // ফরিদপুর
    const Shelter(
      id: 'frd1',
      name: 'ফরিদপুর সরকারি উচ্চ বিদ্যালয়',
      address: 'ফরিদপুর সদর',
      lat: 23.6070,
      lng: 89.8429,
      district: 'faridpur',
      capacity: 600,
    ),
    const Shelter(
      id: 'frd2',
      name: 'মধুখালী বন্যা আশ্রয়কেন্দ্র',
      address: 'মধুখালী, ফরিদপুর',
      lat: 23.5100,
      lng: 89.7100,
      district: 'faridpur',
      capacity: 400,
    ),
    const Shelter(
      id: 'frd3',
      name: 'ভাঙ্গা উপজেলা আশ্রয়কেন্দ্র',
      address: 'ভাঙ্গা, ফরিদপুর',
      lat: 23.4600,
      lng: 89.9800,
      district: 'faridpur',
      capacity: 420,
    ),
    // ফেনী
    const Shelter(
      id: 'fen1',
      name: 'ফেনী সরকারি উচ্চ বিদ্যালয় আশ্রয়কেন্দ্র',
      address: 'ফেনী সদর',
      lat: 23.0159,
      lng: 91.3976,
      district: 'feni',
      capacity: 600,
    ),
    const Shelter(
      id: 'fen2',
      name: 'সোনাগাজী সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'সোনাগাজী, ফেনী',
      lat: 23.0800,
      lng: 91.4100,
      district: 'feni',
      capacity: 450,
    ),
    const Shelter(
      id: 'fen3',
      name: 'ছাগলনাইয়া বন্যা আশ্রয়কেন্দ্র',
      address: 'ছাগলনাইয়া, ফেনী',
      lat: 23.0600,
      lng: 91.3300,
      district: 'feni',
      capacity: 400,
    ),
    // গাইবান্ধা
    const Shelter(
      id: 'gbd1',
      name: 'গাইবান্ধা সরকারি উচ্চ বিদ্যালয়',
      address: 'গাইবান্ধা সদর',
      lat: 25.3288,
      lng: 89.5281,
      district: 'gaibandha',
      capacity: 500,
    ),
    const Shelter(
      id: 'gbd2',
      name: 'সুন্দরগঞ্জ বন্যা আশ্রয়কেন্দ্র',
      address: 'সুন্দরগঞ্জ, গাইবান্ধা',
      lat: 25.3800,
      lng: 89.4800,
      district: 'gaibandha',
      capacity: 380,
    ),
    const Shelter(
      id: 'gbd3',
      name: 'ফুলছড়ি চর আশ্রয়কেন্দ্র',
      address: 'ফুলছড়ি, গাইবান্ধা',
      lat: 25.1900,
      lng: 89.5900,
      district: 'gaibandha',
      capacity: 400,
    ),
    // গাজীপুর
    const Shelter(
      id: 'gzp1',
      name: 'গাজীপুর সদর সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'গাজীপুর সদর',
      lat: 23.9999,
      lng: 90.4203,
      district: 'gazipur',
      capacity: 400,
    ),
    const Shelter(
      id: 'gzp2',
      name: 'কালিয়াকৈর কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'কালিয়াকৈর, গাজীপুর',
      lat: 24.0550,
      lng: 90.2200,
      district: 'gazipur',
      capacity: 350,
    ),
    const Shelter(
      id: 'gzp3',
      name: 'কাপাসিয়া বন্যা আশ্রয়কেন্দ্র',
      address: 'কাপাসিয়া, গাজীপুর',
      lat: 24.1300,
      lng: 90.5800,
      district: 'gazipur',
      capacity: 380,
    ),
    // গোপালগঞ্জ
    const Shelter(
      id: 'gpg1',
      name: 'গোপালগঞ্জ সরকারি উচ্চ বিদ্যালয়',
      address: 'গোপালগঞ্জ সদর',
      lat: 23.0051,
      lng: 89.8266,
      district: 'gopalganj',
      capacity: 550,
    ),
    const Shelter(
      id: 'gpg2',
      name: 'টুঙ্গিপাড়া বন্যা আশ্রয়কেন্দ্র',
      address: 'টুঙ্গিপাড়া, গোপালগঞ্জ',
      lat: 23.0600,
      lng: 89.7500,
      district: 'gopalganj',
      capacity: 380,
    ),
    const Shelter(
      id: 'gpg3',
      name: 'কোটালীপাড়া কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'কোটালীপাড়া, গোপালগঞ্জ',
      lat: 22.9800,
      lng: 89.9500,
      district: 'gopalganj',
      capacity: 360,
    ),
    // হবিগঞ্জ
    const Shelter(
      id: 'hbg1',
      name: 'হবিগঞ্জ সরকারি উচ্চ বিদ্যালয়',
      address: 'হবিগঞ্জ সদর',
      lat: 24.3745,
      lng: 91.4154,
      district: 'habiganj',
      capacity: 550,
    ),
    const Shelter(
      id: 'hbg2',
      name: 'চুনারুঘাট বন্যা আশ্রয়কেন্দ্র',
      address: 'চুনারুঘাট, হবিগঞ্জ',
      lat: 24.2200,
      lng: 91.5200,
      district: 'habiganj',
      capacity: 380,
    ),
    const Shelter(
      id: 'hbg3',
      name: 'বানিয়াচং কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'বানিয়াচং, হবিগঞ্জ',
      lat: 24.5200,
      lng: 91.3500,
      district: 'habiganj',
      capacity: 400,
    ),
    // জামালপুর
    const Shelter(
      id: 'jml1',
      name: 'জামালপুর সরকারি উচ্চ বিদ্যালয়',
      address: 'জামালপুর সদর',
      lat: 24.8949,
      lng: 89.9371,
      district: 'jamalpur',
      capacity: 550,
    ),
    const Shelter(
      id: 'jml2',
      name: 'দেওয়ানগঞ্জ বন্যা আশ্রয়কেন্দ্র',
      address: 'দেওয়ানগঞ্জ, জামালপুর',
      lat: 25.1200,
      lng: 89.8400,
      district: 'jamalpur',
      capacity: 400,
    ),
    const Shelter(
      id: 'jml3',
      name: 'ইসলামপুর চর আশ্রয়কেন্দ্র',
      address: 'ইসলামপুর, জামালপুর',
      lat: 24.8200,
      lng: 89.8000,
      district: 'jamalpur',
      capacity: 380,
    ),
    // যশোর
    const Shelter(
      id: 'jsr1',
      name: 'যশোর জিলা স্কুল আশ্রয়কেন্দ্র',
      address: 'যশোর সদর',
      lat: 23.1664,
      lng: 89.2121,
      district: 'jessore',
      capacity: 650,
    ),
    const Shelter(
      id: 'jsr2',
      name: 'অভয়নগর বন্যা আশ্রয়কেন্দ্র',
      address: 'অভয়নগর, যশোর',
      lat: 23.0200,
      lng: 89.3500,
      district: 'jessore',
      capacity: 400,
    ),
    const Shelter(
      id: 'jsr3',
      name: 'চৌগাছা সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'চৌগাছা, যশোর',
      lat: 23.1700,
      lng: 88.9800,
      district: 'jessore',
      capacity: 420,
    ),
    // ঝালকাঠি
    const Shelter(
      id: 'jlk1',
      name: 'ঝালকাঠি সরকারি উচ্চ বিদ্যালয়',
      address: 'ঝালকাঠি সদর',
      lat: 22.6406,
      lng: 90.1983,
      district: 'jhalokati',
      capacity: 500,
    ),
    const Shelter(
      id: 'jlk2',
      name: 'নলছিটি সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'নলছিটি, ঝালকাঠি',
      lat: 22.6900,
      lng: 90.1200,
      district: 'jhalokati',
      capacity: 380,
    ),
    const Shelter(
      id: 'jlk3',
      name: 'রাজাপুর উপকূলীয় আশ্রয়কেন্দ্র',
      address: 'রাজাপুর, ঝালকাঠি',
      lat: 22.5500,
      lng: 90.1500,
      district: 'jhalokati',
      capacity: 360,
    ),
    // ঝিনাইদহ
    const Shelter(
      id: 'jnd1',
      name: 'ঝিনাইদহ সরকারি কলেজ আশ্রয়কেন্দ্র',
      address: 'ঝিনাইদহ সদর',
      lat: 23.5449,
      lng: 89.1524,
      district: 'jhenaidah',
      capacity: 550,
    ),
    const Shelter(
      id: 'jnd2',
      name: 'শৈলকুপা বন্যা আশ্রয়কেন্দ্র',
      address: 'শৈলকুপা, ঝিনাইদহ',
      lat: 23.6700,
      lng: 89.0500,
      district: 'jhenaidah',
      capacity: 380,
    ),
    const Shelter(
      id: 'jnd3',
      name: 'কোটচাঁদপুর কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'কোটচাঁদপুর, ঝিনাইদহ',
      lat: 23.4800,
      lng: 88.9500,
      district: 'jhenaidah',
      capacity: 360,
    ),
    // জয়পুরহাট
    const Shelter(
      id: 'jyp1',
      name: 'জয়পুরহাট সরকারি উচ্চ বিদ্যালয়',
      address: 'জয়পুরহাট সদর',
      lat: 25.0974,
      lng: 89.0222,
      district: 'joypurhat',
      capacity: 480,
    ),
    const Shelter(
      id: 'jyp2',
      name: 'আক্কেলপুর বন্যা আশ্রয়কেন্দ্র',
      address: 'আক্কেলপুর, জয়পুরহাট',
      lat: 25.0200,
      lng: 89.0100,
      district: 'joypurhat',
      capacity: 350,
    ),
    const Shelter(
      id: 'jyp3',
      name: 'পাঁচবিবি কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'পাঁচবিবি, জয়পুরহাট',
      lat: 25.1600,
      lng: 89.0700,
      district: 'joypurhat',
      capacity: 340,
    ),
    // খাগড়াছড়ি
    const Shelter(
      id: 'kgc1',
      name: 'খাগড়াছড়ি সরকারি উচ্চ বিদ্যালয়',
      address: 'খাগড়াছড়ি সদর',
      lat: 23.1193,
      lng: 91.9847,
      district: 'khagrachhari',
      capacity: 400,
    ),
    const Shelter(
      id: 'kgc2',
      name: 'দিঘিনালা কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'দিঘিনালা, খাগড়াছড়ি',
      lat: 23.2200,
      lng: 92.0700,
      district: 'khagrachhari',
      capacity: 300,
    ),
    const Shelter(
      id: 'kgc3',
      name: 'রামগড় বন্যা আশ্রয়কেন্দ্র',
      address: 'রামগড়, খাগড়াছড়ি',
      lat: 22.9900,
      lng: 91.9400,
      district: 'khagrachhari',
      capacity: 280,
    ),
    // খুলনা
    const Shelter(
      id: 'khl1',
      name: 'খুলনা জিলা স্কুল',
      address: 'KDA Avenue, খুলনা',
      lat: 22.8456,
      lng: 89.5403,
      district: 'khulna',
      capacity: 700,
    ),
    const Shelter(
      id: 'khl2',
      name: 'খালিশপুর সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'খালিশপুর, খুলনা',
      lat: 22.8710,
      lng: 89.5100,
      district: 'khulna',
      capacity: 500,
    ),
    const Shelter(
      id: 'khl3',
      name: 'দৌলতপুর কমিউনিটি সেন্টার',
      address: 'দৌলতপুর, খুলনা',
      lat: 22.9000,
      lng: 89.5300,
      district: 'khulna',
      capacity: 400,
    ),
    // কিশোরগঞ্জ
    const Shelter(
      id: 'ksg1',
      name: 'কিশোরগঞ্জ সরকারি উচ্চ বিদ্যালয়',
      address: 'কিশোরগঞ্জ সদর',
      lat: 24.4449,
      lng: 90.7767,
      district: 'kishoreganj',
      capacity: 600,
    ),
    const Shelter(
      id: 'ksg2',
      name: 'বাজিতপুর বন্যা আশ্রয়কেন্দ্র',
      address: 'বাজিতপুর, কিশোরগঞ্জ',
      lat: 24.2200,
      lng: 90.9500,
      district: 'kishoreganj',
      capacity: 420,
    ),
    const Shelter(
      id: 'ksg3',
      name: 'ইটনা হাওর আশ্রয়কেন্দ্র',
      address: 'ইটনা, কিশোরগঞ্জ',
      lat: 24.5900,
      lng: 90.9700,
      district: 'kishoreganj',
      capacity: 400,
    ),
    // কুড়িগ্রাম
    const Shelter(
      id: 'krg1',
      name: 'কুড়িগ্রাম সরকারি উচ্চ বিদ্যালয়',
      address: 'কুড়িগ্রাম সদর',
      lat: 25.8482,
      lng: 89.6363,
      district: 'kurigram',
      capacity: 500,
    ),
    const Shelter(
      id: 'krg2',
      name: 'উলিপুর চর আশ্রয়কেন্দ্র',
      address: 'উলিপুর, কুড়িগ্রাম',
      lat: 25.6700,
      lng: 89.6700,
      district: 'kurigram',
      capacity: 380,
    ),
    const Shelter(
      id: 'krg3',
      name: 'রৌমারী বন্যা আশ্রয়কেন্দ্র',
      address: 'রৌমারী, কুড়িগ্রাম',
      lat: 25.6000,
      lng: 89.7700,
      district: 'kurigram',
      capacity: 360,
    ),
    // কুষ্টিয়া
    const Shelter(
      id: 'kst1',
      name: 'কুষ্টিয়া সরকারি কলেজ আশ্রয়কেন্দ্র',
      address: 'কুষ্টিয়া সদর',
      lat: 23.9013,
      lng: 89.1194,
      district: 'kushtia',
      capacity: 600,
    ),
    const Shelter(
      id: 'kst2',
      name: 'কুমারখালী বন্যা আশ্রয়কেন্দ্র',
      address: 'কুমারখালী, কুষ্টিয়া',
      lat: 23.8700,
      lng: 89.1900,
      district: 'kushtia',
      capacity: 400,
    ),
    const Shelter(
      id: 'kst3',
      name: 'খোকসা কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'খোকসা, কুষ্টিয়া',
      lat: 23.7600,
      lng: 89.0600,
      district: 'kushtia',
      capacity: 380,
    ),
    // লক্ষ্মীপুর
    const Shelter(
      id: 'lkp1',
      name: 'লক্ষ্মীপুর সরকারি উচ্চ বিদ্যালয়',
      address: 'লক্ষ্মীপুর সদর',
      lat: 22.9418,
      lng: 90.8412,
      district: 'lakshmipur',
      capacity: 600,
    ),
    const Shelter(
      id: 'lkp2',
      name: 'রামগতি সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'রামগতি, লক্ষ্মীপুর',
      lat: 22.7700,
      lng: 90.8600,
      district: 'lakshmipur',
      capacity: 500,
    ),
    const Shelter(
      id: 'lkp3',
      name: 'কমলনগর উপকূলীয় আশ্রয়কেন্দ্র',
      address: 'কমলনগর, লক্ষ্মীপুর',
      lat: 22.7200,
      lng: 90.9100,
      district: 'lakshmipur',
      capacity: 480,
    ),
    // লালমনিরহাট
    const Shelter(
      id: 'lmn1',
      name: 'লালমনিরহাট সরকারি উচ্চ বিদ্যালয়',
      address: 'লালমনিরহাট সদর',
      lat: 25.9923,
      lng: 89.2847,
      district: 'lalmonirhat',
      capacity: 500,
    ),
    const Shelter(
      id: 'lmn2',
      name: 'হাতিবান্ধা বন্যা আশ্রয়কেন্দ্র',
      address: 'হাতিবান্ধা, লালমনিরহাট',
      lat: 26.0400,
      lng: 89.0800,
      district: 'lalmonirhat',
      capacity: 360,
    ),
    const Shelter(
      id: 'lmn3',
      name: 'পাটগ্রাম চর আশ্রয়কেন্দ্র',
      address: 'পাটগ্রাম, লালমনিরহাট',
      lat: 26.1500,
      lng: 88.9900,
      district: 'lalmonirhat',
      capacity: 350,
    ),
    // মাদারীপুর
    const Shelter(
      id: 'mdr1',
      name: 'মাদারীপুর সরকারি উচ্চ বিদ্যালয়',
      address: 'মাদারীপুর সদর',
      lat: 23.1643,
      lng: 90.1982,
      district: 'madaripur',
      capacity: 550,
    ),
    const Shelter(
      id: 'mdr2',
      name: 'শিবচর বন্যা আশ্রয়কেন্দ্র',
      address: 'শিবচর, মাদারীপুর',
      lat: 23.2200,
      lng: 90.3000,
      district: 'madaripur',
      capacity: 420,
    ),
    const Shelter(
      id: 'mdr3',
      name: 'রাজৈর সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'রাজৈর, মাদারীপুর',
      lat: 23.1100,
      lng: 90.1200,
      district: 'madaripur',
      capacity: 400,
    ),
    // মাগুরা
    const Shelter(
      id: 'mgr1',
      name: 'মাগুরা সরকারি উচ্চ বিদ্যালয়',
      address: 'মাগুরা সদর',
      lat: 23.4873,
      lng: 89.4192,
      district: 'magura',
      capacity: 500,
    ),
    const Shelter(
      id: 'mgr2',
      name: 'শালিখা বন্যা আশ্রয়কেন্দ্র',
      address: 'শালিখা, মাগুরা',
      lat: 23.5300,
      lng: 89.5400,
      district: 'magura',
      capacity: 360,
    ),
    const Shelter(
      id: 'mgr3',
      name: 'মোহাম্মদপুর কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'মোহাম্মদপুর, মাগুরা',
      lat: 23.3900,
      lng: 89.4500,
      district: 'magura',
      capacity: 340,
    ),
    // মানিকগঞ্জ
    const Shelter(
      id: 'mkg1',
      name: 'মানিকগঞ্জ সরকারি উচ্চ বিদ্যালয়',
      address: 'মানিকগঞ্জ সদর',
      lat: 23.8634,
      lng: 90.0021,
      district: 'manikganj',
      capacity: 550,
    ),
    const Shelter(
      id: 'mkg2',
      name: 'শিবালয় বন্যা আশ্রয়কেন্দ্র',
      address: 'শিবালয়, মানিকগঞ্জ',
      lat: 23.8900,
      lng: 89.8200,
      district: 'manikganj',
      capacity: 380,
    ),
    const Shelter(
      id: 'mkg3',
      name: 'ঘিওর চর আশ্রয়কেন্দ্র',
      address: 'ঘিওর, মানিকগঞ্জ',
      lat: 23.7900,
      lng: 89.9200,
      district: 'manikganj',
      capacity: 360,
    ),
    // মেহেরপুর
    const Shelter(
      id: 'mhp1',
      name: 'মেহেরপুর সরকারি উচ্চ বিদ্যালয়',
      address: 'মেহেরপুর সদর',
      lat: 23.7623,
      lng: 88.6317,
      district: 'meherpur',
      capacity: 480,
    ),
    const Shelter(
      id: 'mhp2',
      name: 'গাংনী বন্যা আশ্রয়কেন্দ্র',
      address: 'গাংনী, মেহেরপুর',
      lat: 23.7900,
      lng: 88.6900,
      district: 'meherpur',
      capacity: 340,
    ),
    const Shelter(
      id: 'mhp3',
      name: 'মুজিবনগর কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'মুজিবনগর, মেহেরপুর',
      lat: 23.7200,
      lng: 88.5600,
      district: 'meherpur',
      capacity: 320,
    ),
    // মৌলভীবাজার
    const Shelter(
      id: 'mlb1',
      name: 'মৌলভীবাজার সরকারি উচ্চ বিদ্যালয়',
      address: 'মৌলভীবাজার সদর',
      lat: 24.4829,
      lng: 91.7774,
      district: 'moulvibazar',
      capacity: 550,
    ),
    const Shelter(
      id: 'mlb2',
      name: 'শ্রীমঙ্গল বন্যা আশ্রয়কেন্দ্র',
      address: 'শ্রীমঙ্গল, মৌলভীবাজার',
      lat: 24.3100,
      lng: 91.7200,
      district: 'moulvibazar',
      capacity: 400,
    ),
    const Shelter(
      id: 'mlb3',
      name: 'কুলাউড়া কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'কুলাউড়া, মৌলভীবাজার',
      lat: 24.5600,
      lng: 92.0300,
      district: 'moulvibazar',
      capacity: 380,
    ),
    // মুন্সিগঞ্জ
    const Shelter(
      id: 'msj1',
      name: 'মুন্সিগঞ্জ সরকারি উচ্চ বিদ্যালয়',
      address: 'মুন্সিগঞ্জ সদর',
      lat: 23.5422,
      lng: 90.5307,
      district: 'munshiganj',
      capacity: 550,
    ),
    const Shelter(
      id: 'msj2',
      name: 'গজারিয়া বন্যা আশ্রয়কেন্দ্র',
      address: 'গজারিয়া, মুন্সিগঞ্জ',
      lat: 23.5100,
      lng: 90.5900,
      district: 'munshiganj',
      capacity: 380,
    ),
    const Shelter(
      id: 'msj3',
      name: 'শ্রীনগর সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'শ্রীনগর, মুন্সিগঞ্জ',
      lat: 23.6300,
      lng: 90.4300,
      district: 'munshiganj',
      capacity: 360,
    ),
    // ময়মনসিংহ
    const Shelter(
      id: 'mym1',
      name: 'ময়মনসিংহ জিলা স্কুল',
      address: 'ময়মনসিংহ শহর',
      lat: 24.7471,
      lng: 90.4203,
      district: 'mymensingh',
      capacity: 650,
    ),
    const Shelter(
      id: 'mym2',
      name: 'হালুয়াঘাট বন্যা আশ্রয়কেন্দ্র',
      address: 'হালুয়াঘাট, ময়মনসিংহ',
      lat: 25.0200,
      lng: 90.2200,
      district: 'mymensingh',
      capacity: 420,
    ),
    const Shelter(
      id: 'mym3',
      name: 'গফরগাঁও কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'গফরগাঁও, ময়মনসিংহ',
      lat: 24.4700,
      lng: 90.5700,
      district: 'mymensingh',
      capacity: 400,
    ),
    // নওগাঁ
    const Shelter(
      id: 'nog1',
      name: 'নওগাঁ সরকারি উচ্চ বিদ্যালয়',
      address: 'নওগাঁ সদর',
      lat: 24.7936,
      lng: 88.9315,
      district: 'naogaon',
      capacity: 550,
    ),
    const Shelter(
      id: 'nog2',
      name: 'আত্রাই বন্যা আশ্রয়কেন্দ্র',
      address: 'আত্রাই, নওগাঁ',
      lat: 24.7200,
      lng: 88.9800,
      district: 'naogaon',
      capacity: 380,
    ),
    const Shelter(
      id: 'nog3',
      name: 'বদলগাছী কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'বদলগাছী, নওগাঁ',
      lat: 24.9100,
      lng: 88.8700,
      district: 'naogaon',
      capacity: 360,
    ),
    // নড়াইল
    const Shelter(
      id: 'nrl1',
      name: 'নড়াইল সরকারি উচ্চ বিদ্যালয়',
      address: 'নড়াইল সদর',
      lat: 23.1724,
      lng: 89.5124,
      district: 'narail',
      capacity: 500,
    ),
    const Shelter(
      id: 'nrl2',
      name: 'লোহাগাড়া বন্যা আশ্রয়কেন্দ্র',
      address: 'লোহাগাড়া, নড়াইল',
      lat: 23.0400,
      lng: 89.5500,
      district: 'narail',
      capacity: 360,
    ),
    const Shelter(
      id: 'nrl3',
      name: 'কালিয়া কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'কালিয়া, নড়াইল',
      lat: 23.2000,
      lng: 89.6600,
      district: 'narail',
      capacity: 340,
    ),
    // নারায়ণগঞ্জ
    const Shelter(
      id: 'nrj1',
      name: 'নারায়ণগঞ্জ Govt. Tolaram College',
      address: 'নারায়ণগঞ্জ সদর',
      lat: 23.6238,
      lng: 90.4996,
      district: 'narayanganj',
      capacity: 700,
    ),
    const Shelter(
      id: 'nrj2',
      name: 'রূপগঞ্জ বন্যা আশ্রয়কেন্দ্র',
      address: 'রূপগঞ্জ, নারায়ণগঞ্জ',
      lat: 23.7500,
      lng: 90.6100,
      district: 'narayanganj',
      capacity: 450,
    ),
    const Shelter(
      id: 'nrj3',
      name: 'আড়াইহাজার কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'আড়াইহাজার, নারায়ণগঞ্জ',
      lat: 23.6800,
      lng: 90.6700,
      district: 'narayanganj',
      capacity: 420,
    ),
    // নরসিংদী
    const Shelter(
      id: 'nsd1',
      name: 'নরসিংদী সরকারি উচ্চ বিদ্যালয়',
      address: 'নরসিংদী সদর',
      lat: 23.9324,
      lng: 90.7150,
      district: 'narsingdi',
      capacity: 550,
    ),
    const Shelter(
      id: 'nsd2',
      name: 'রায়পুরা বন্যা আশ্রয়কেন্দ্র',
      address: 'রায়পুরা, নরসিংদী',
      lat: 23.9600,
      lng: 90.8500,
      district: 'narsingdi',
      capacity: 400,
    ),
    const Shelter(
      id: 'nsd3',
      name: 'মনোহরদী কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'মনোহরদী, নরসিংদী',
      lat: 24.0600,
      lng: 90.6800,
      district: 'narsingdi',
      capacity: 380,
    ),
    // নাটোর
    const Shelter(
      id: 'ntr1',
      name: 'নাটোর সরকারি উচ্চ বিদ্যালয়',
      address: 'নাটোর সদর',
      lat: 24.4204,
      lng: 88.9882,
      district: 'natore',
      capacity: 520,
    ),
    const Shelter(
      id: 'ntr2',
      name: 'বড়াইগ্রাম বন্যা আশ্রয়কেন্দ্র',
      address: 'বড়াইগ্রাম, নাটোর',
      lat: 24.3500,
      lng: 89.1800,
      district: 'natore',
      capacity: 380,
    ),
    const Shelter(
      id: 'ntr3',
      name: 'গুরুদাসপুর কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'গুরুদাসপুর, নাটোর',
      lat: 24.2900,
      lng: 89.0200,
      district: 'natore',
      capacity: 360,
    ),
    // নেত্রকোনা
    const Shelter(
      id: 'ntk1',
      name: 'নেত্রকোনা সরকারি উচ্চ বিদ্যালয়',
      address: 'নেত্রকোনা সদর',
      lat: 24.8703,
      lng: 90.7203,
      district: 'netrokona',
      capacity: 520,
    ),
    const Shelter(
      id: 'ntk2',
      name: 'মোহনগঞ্জ হাওর আশ্রয়কেন্দ্র',
      address: 'মোহনগঞ্জ, নেত্রকোনা',
      lat: 24.8800,
      lng: 91.0200,
      district: 'netrokona',
      capacity: 400,
    ),
    const Shelter(
      id: 'ntk3',
      name: 'খালিয়াজুরি বন্যা আশ্রয়কেন্দ্র',
      address: 'খালিয়াজুরি, নেত্রকোনা',
      lat: 24.6600,
      lng: 91.0400,
      district: 'netrokona',
      capacity: 380,
    ),
    // নীলফামারী
    const Shelter(
      id: 'nlp1',
      name: 'নীলফামারী সরকারি উচ্চ বিদ্যালয়',
      address: 'নীলফামারী সদর',
      lat: 25.9318,
      lng: 88.8560,
      district: 'nilphamari',
      capacity: 500,
    ),
    const Shelter(
      id: 'nlp2',
      name: 'সৈয়দপুর বন্যা আশ্রয়কেন্দ্র',
      address: 'সৈয়দপুর, নীলফামারী',
      lat: 25.7800,
      lng: 88.8900,
      district: 'nilphamari',
      capacity: 400,
    ),
    const Shelter(
      id: 'nlp3',
      name: 'জলঢাকা চর আশ্রয়কেন্দ্র',
      address: 'জলঢাকা, নীলফামারী',
      lat: 26.0200,
      lng: 88.9100,
      district: 'nilphamari',
      capacity: 360,
    ),
    // নোয়াখালী
    const Shelter(
      id: 'nkl1',
      name: 'নোয়াখালী সরকারি কলেজ আশ্রয়কেন্দ্র',
      address: 'Maijdee, নোয়াখালী',
      lat: 22.8696,
      lng: 91.0993,
      district: 'noakhali',
      capacity: 700,
    ),
    const Shelter(
      id: 'nkl2',
      name: 'হাতিয়া দ্বীপ সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'হাতিয়া, নোয়াখালী',
      lat: 22.3500,
      lng: 91.1000,
      district: 'noakhali',
      capacity: 800,
    ),
    const Shelter(
      id: 'nkl3',
      name: 'সুবর্ণচর উপকূলীয় আশ্রয়কেন্দ্র',
      address: 'সুবর্ণচর, নোয়াখালী',
      lat: 22.5500,
      lng: 91.3000,
      district: 'noakhali',
      capacity: 600,
    ),
    // পাবনা
    const Shelter(
      id: 'pbn1',
      name: 'পাবনা সরকারি উচ্চ বিদ্যালয়',
      address: 'পাবনা সদর',
      lat: 24.0063,
      lng: 89.2372,
      district: 'pabna',
      capacity: 580,
    ),
    const Shelter(
      id: 'pbn2',
      name: 'ঈশ্বরদী বন্যা আশ্রয়কেন্দ্র',
      address: 'ঈশ্বরদী, পাবনা',
      lat: 24.1300,
      lng: 89.0600,
      district: 'pabna',
      capacity: 400,
    ),
    const Shelter(
      id: 'pbn3',
      name: 'বেড়া চর আশ্রয়কেন্দ্র',
      address: 'বেড়া, পাবনা',
      lat: 24.0900,
      lng: 89.5200,
      district: 'pabna',
      capacity: 380,
    ),
    // পঞ্চগড়
    const Shelter(
      id: 'pcg1',
      name: 'পঞ্চগড় সরকারি উচ্চ বিদ্যালয়',
      address: 'পঞ্চগড় সদর',
      lat: 26.3411,
      lng: 88.5542,
      district: 'panchagarh',
      capacity: 460,
    ),
    const Shelter(
      id: 'pcg2',
      name: 'তেতুলিয়া বন্যা আশ্রয়কেন্দ্র',
      address: 'তেতুলিয়া, পঞ্চগড়',
      lat: 26.6200,
      lng: 88.6100,
      district: 'panchagarh',
      capacity: 330,
    ),
    const Shelter(
      id: 'pcg3',
      name: 'আটোয়ারি কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'আটোয়ারি, পঞ্চগড়',
      lat: 26.3100,
      lng: 88.6400,
      district: 'panchagarh',
      capacity: 310,
    ),
    // পটুয়াখালী
    const Shelter(
      id: 'ptk1',
      name: 'পটুয়াখালী সরকারি কলেজ আশ্রয়কেন্দ্র',
      address: 'পটুয়াখালী শহর',
      lat: 22.3596,
      lng: 90.3290,
      district: 'patuakhali',
      capacity: 700,
    ),
    const Shelter(
      id: 'ptk2',
      name: 'কুয়াকাটা সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'কুয়াকাটা, পটুয়াখালী',
      lat: 21.8180,
      lng: 90.1180,
      district: 'patuakhali',
      capacity: 500,
    ),
    const Shelter(
      id: 'ptk3',
      name: 'গলাচিপা উপকূলীয় আশ্রয়কেন্দ্র',
      address: 'গলাচিপা, পটুয়াখালী',
      lat: 22.1900,
      lng: 90.4300,
      district: 'patuakhali',
      capacity: 550,
    ),
    // পিরোজপুর
    const Shelter(
      id: 'prj1',
      name: 'পিরোজপুর সরকারি উচ্চ বিদ্যালয়',
      address: 'পিরোজপুর সদর',
      lat: 22.5841,
      lng: 89.9758,
      district: 'pirojpur',
      capacity: 550,
    ),
    const Shelter(
      id: 'prj2',
      name: 'মঠবাড়িয়া সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'মঠবাড়িয়া, পিরোজপুর',
      lat: 22.2900,
      lng: 89.9200,
      district: 'pirojpur',
      capacity: 450,
    ),
    const Shelter(
      id: 'prj3',
      name: 'ভান্ডারিয়া উপকূলীয় আশ্রয়কেন্দ্র',
      address: 'ভান্ডারিয়া, পিরোজপুর',
      lat: 22.4900,
      lng: 90.0600,
      district: 'pirojpur',
      capacity: 420,
    ),
    // রাজবাড়ী
    const Shelter(
      id: 'rjb1',
      name: 'রাজবাড়ী সরকারি উচ্চ বিদ্যালয়',
      address: 'রাজবাড়ী সদর',
      lat: 23.7574,
      lng: 89.6444,
      district: 'rajbari',
      capacity: 520,
    ),
    const Shelter(
      id: 'rjb2',
      name: 'গোয়ালন্দঘাট বন্যা আশ্রয়কেন্দ্র',
      address: 'গোয়ালন্দঘাট, রাজবাড়ী',
      lat: 23.6900,
      lng: 89.7800,
      district: 'rajbari',
      capacity: 380,
    ),
    const Shelter(
      id: 'rjb3',
      name: 'পাংশা কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'পাংশা, রাজবাড়ী',
      lat: 23.7900,
      lng: 89.7400,
      district: 'rajbari',
      capacity: 360,
    ),
    // রাজশাহী
    const Shelter(
      id: 'rjs1',
      name: 'রাজশাহী কলেজিয়েট স্কুল',
      address: 'রাজশাহী শহর',
      lat: 24.3745,
      lng: 88.6042,
      district: 'rajshahi',
      capacity: 700,
    ),
    const Shelter(
      id: 'rjs2',
      name: 'পুঠিয়া বন্যা আশ্রয়কেন্দ্র',
      address: 'পুঠিয়া, রাজশাহী',
      lat: 24.3900,
      lng: 88.7700,
      district: 'rajshahi',
      capacity: 420,
    ),
    const Shelter(
      id: 'rjs3',
      name: 'গোদাগাড়ী কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'গোদাগাড়ী, রাজশাহী',
      lat: 24.5000,
      lng: 88.3700,
      district: 'rajshahi',
      capacity: 400,
    ),
    // রাঙ্গামাটি
    const Shelter(
      id: 'ram1',
      name: 'রাঙ্গামাটি সরকারি উচ্চ বিদ্যালয়',
      address: 'রাঙ্গামাটি সদর',
      lat: 22.7324,
      lng: 92.2985,
      district: 'rangamati',
      capacity: 420,
    ),
    const Shelter(
      id: 'ram2',
      name: 'কাপ্তাই বন্যা আশ্রয়কেন্দ্র',
      address: 'কাপ্তাই, রাঙ্গামাটি',
      lat: 22.5100,
      lng: 92.2900,
      district: 'rangamati',
      capacity: 320,
    ),
    const Shelter(
      id: 'ram3',
      name: 'বিলাইছড়ি কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'বিলাইছড়ি, রাঙ্গামাটি',
      lat: 22.5700,
      lng: 92.3500,
      district: 'rangamati',
      capacity: 300,
    ),
    // রংপুর
    const Shelter(
      id: 'rgp1',
      name: 'রংপুর জিলা স্কুল আশ্রয়কেন্দ্র',
      address: 'রংপুর শহর',
      lat: 25.7439,
      lng: 89.2752,
      district: 'rangpur',
      capacity: 600,
    ),
    const Shelter(
      id: 'rgp2',
      name: 'পীরগঞ্জ বন্যা আশ্রয়কেন্দ্র',
      address: 'পীরগঞ্জ, রংপুর',
      lat: 25.8500,
      lng: 89.3500,
      district: 'rangpur',
      capacity: 400,
    ),
    const Shelter(
      id: 'rgp3',
      name: 'গঙ্গাচড়া চর আশ্রয়কেন্দ্র',
      address: 'গঙ্গাচড়া, রংপুর',
      lat: 25.7300,
      lng: 89.5200,
      district: 'rangpur',
      capacity: 380,
    ),
    // সাতক্ষীরা
    const Shelter(
      id: 'stk1',
      name: 'সাতক্ষীরা সরকারি উচ্চ বিদ্যালয়',
      address: 'সাতক্ষীরা সদর',
      lat: 22.7185,
      lng: 89.0705,
      district: 'satkhira',
      capacity: 600,
    ),
    const Shelter(
      id: 'stk2',
      name: 'শ্যামনগর সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'শ্যামনগর, সাতক্ষীরা',
      lat: 22.2200,
      lng: 89.0600,
      district: 'satkhira',
      capacity: 500,
    ),
    const Shelter(
      id: 'stk3',
      name: 'আশাশুনি উপকূলীয় আশ্রয়কেন্দ্র',
      address: 'আশাশুনি, সাতক্ষীরা',
      lat: 22.6700,
      lng: 89.2800,
      district: 'satkhira',
      capacity: 450,
    ),
    // শরীয়তপুর
    const Shelter(
      id: 'srt1',
      name: 'শরীয়তপুর সরকারি উচ্চ বিদ্যালয়',
      address: 'শরীয়তপুর সদর',
      lat: 23.2424,
      lng: 90.4352,
      district: 'shariatpur',
      capacity: 530,
    ),
    const Shelter(
      id: 'srt2',
      name: 'নড়িয়া বন্যা আশ্রয়কেন্দ্র',
      address: 'নড়িয়া, শরীয়তপুর',
      lat: 23.1600,
      lng: 90.5500,
      district: 'shariatpur',
      capacity: 380,
    ),
    const Shelter(
      id: 'srt3',
      name: 'গোসাইরহাট সাইক্লোন আশ্রয়কেন্দ্র',
      address: 'গোসাইরহাট, শরীয়তপুর',
      lat: 23.0500,
      lng: 90.4100,
      district: 'shariatpur',
      capacity: 360,
    ),
    // শেরপুর
    const Shelter(
      id: 'shp1',
      name: 'শেরপুর সরকারি উচ্চ বিদ্যালয়',
      address: 'শেরপুর সদর',
      lat: 25.0204,
      lng: 90.0157,
      district: 'sherpur',
      capacity: 520,
    ),
    const Shelter(
      id: 'shp2',
      name: 'নালিতাবাড়ী বন্যা আশ্রয়কেন্দ্র',
      address: 'নালিতাবাড়ী, শেরপুর',
      lat: 25.0900,
      lng: 90.1400,
      district: 'sherpur',
      capacity: 380,
    ),
    const Shelter(
      id: 'shp3',
      name: 'ঝিনাইগাতী কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'ঝিনাইগাতী, শেরপুর',
      lat: 25.0100,
      lng: 90.2200,
      district: 'sherpur',
      capacity: 360,
    ),
    // সিরাজগঞ্জ
    const Shelter(
      id: 'srg1',
      name: 'সিরাজগঞ্জ সরকারি উচ্চ বিদ্যালয়',
      address: 'সিরাজগঞ্জ সদর',
      lat: 24.4534,
      lng: 89.7006,
      district: 'sirajganj',
      capacity: 600,
    ),
    const Shelter(
      id: 'srg2',
      name: 'কাজিপুর চর আশ্রয়কেন্দ্র',
      address: 'কাজিপুর, সিরাজগঞ্জ',
      lat: 24.6300,
      lng: 89.7200,
      district: 'sirajganj',
      capacity: 450,
    ),
    const Shelter(
      id: 'srg3',
      name: 'চৌহালি বন্যা আশ্রয়কেন্দ্র',
      address: 'চৌহালি, সিরাজগঞ্জ',
      lat: 24.3300,
      lng: 89.8600,
      district: 'sirajganj',
      capacity: 420,
    ),
    // সুনামগঞ্জ
    const Shelter(
      id: 'snj1',
      name: 'সুনামগঞ্জ সরকারি উচ্চ বিদ্যালয়',
      address: 'সুনামগঞ্জ সদর',
      lat: 25.0658,
      lng: 91.3950,
      district: 'sunamganj',
      capacity: 540,
    ),
    const Shelter(
      id: 'snj2',
      name: 'তাহিরপুর হাওর আশ্রয়কেন্দ্র',
      address: 'তাহিরপুর, সুনামগঞ্জ',
      lat: 24.9900,
      lng: 91.5500,
      district: 'sunamganj',
      capacity: 400,
    ),
    const Shelter(
      id: 'snj3',
      name: 'ধর্মপাশা বন্যা আশ্রয়কেন্দ্র',
      address: 'ধর্মপাশা, সুনামগঞ্জ',
      lat: 24.9100,
      lng: 91.1700,
      district: 'sunamganj',
      capacity: 380,
    ),
    // সিলেট
    const Shelter(
      id: 'syl1',
      name: 'সিলেট Govt. Pilot High School',
      address: 'সিলেট শহর',
      lat: 24.8949,
      lng: 91.8687,
      district: 'sylhet',
      capacity: 750,
    ),
    const Shelter(
      id: 'syl2',
      name: 'MC College বন্যা আশ্রয়কেন্দ্র',
      address: 'Ambarkhana, সিলেট',
      lat: 24.9000,
      lng: 91.8800,
      district: 'sylhet',
      capacity: 500,
    ),
    const Shelter(
      id: 'syl3',
      name: 'Companiganj কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'Companiganj, সিলেট',
      lat: 24.9900,
      lng: 91.6900,
      district: 'sylhet',
      capacity: 420,
    ),
    // টাঙ্গাইল
    const Shelter(
      id: 'tng1',
      name: 'টাঙ্গাইল সরকারি উচ্চ বিদ্যালয়',
      address: 'টাঙ্গাইল সদর',
      lat: 24.2513,
      lng: 89.9167,
      district: 'tangail',
      capacity: 600,
    ),
    const Shelter(
      id: 'tng2',
      name: 'Bhuapur চর আশ্রয়কেন্দ্র',
      address: 'Bhuapur, টাঙ্গাইল',
      lat: 24.3600,
      lng: 89.8000,
      district: 'tangail',
      capacity: 430,
    ),
    const Shelter(
      id: 'tng3',
      name: 'Nagarpur বন্যা আশ্রয়কেন্দ্র',
      address: 'Nagarpur, টাঙ্গাইল',
      lat: 24.0700,
      lng: 89.8300,
      district: 'tangail',
      capacity: 400,
    ),
    // ঠাকুরগাঁও
    const Shelter(
      id: 'tkg1',
      name: 'ঠাকুরগাঁও সরকারি উচ্চ বিদ্যালয়',
      address: 'ঠাকুরগাঁও সদর',
      lat: 26.0336,
      lng: 88.4616,
      district: 'thakurgaon',
      capacity: 500,
    ),
    const Shelter(
      id: 'tkg2',
      name: 'পীরগঞ্জ বন্যা আশ্রয়কেন্দ্র',
      address: 'পীরগঞ্জ, ঠাকুরগাঁও',
      lat: 25.8700,
      lng: 88.3700,
      district: 'thakurgaon',
      capacity: 360,
    ),
    const Shelter(
      id: 'tkg3',
      name: 'Ranisankail কমিউনিটি আশ্রয়কেন্দ্র',
      address: 'Ranisankail, ঠাকুরগাঁও',
      lat: 26.0000,
      lng: 88.5500,
      district: 'thakurgaon',
      capacity: 340,
    ),
  ];

  Future<List<Shelter>> fetchSheltersByDistrict(String district) async {
    final filtered = _seedShelters
        .where((s) => s.district == district.toLowerCase())
        .toList();
    if (filtered.isEmpty) return _seedShelters.take(3).toList();
    return filtered;
  }

  List<Shelter> nearestShelters(
    double userLat,
    double userLng,
    List<Shelter> allShelters, {
    int count = 3,
  }) {
    if (allShelters.isEmpty) return [];
    final sorted = List<Shelter>.from(allShelters)
      ..sort(
        (a, b) => _distanceKm(
          userLat,
          userLng,
          a.lat,
          a.lng,
        ).compareTo(_distanceKm(userLat, userLng, b.lat, b.lng)),
      );
    return sorted.take(count).toList();
  }

  double distanceTo(double userLat, double userLng, Shelter shelter) =>
      _distanceKm(userLat, userLng, shelter.lat, shelter.lng);

  double _distanceKm(double lat1, double lon1, double lat2, double lon2) {
    const r = 6371.0;
    final dLat = _rad(lat2 - lat1);
    final dLon = _rad(lon2 - lon1);
    final a =
        sin(dLat / 2) * sin(dLat / 2) +
        cos(_rad(lat1)) * cos(_rad(lat2)) * sin(dLon / 2) * sin(dLon / 2);
    return r * 2 * atan2(sqrt(a), sqrt(1 - a));
  }

  double _rad(double deg) => deg * pi / 180;
}
